"""The full menu: categories, items, ingredients, and modifiers.

Kept apart from seed.py so the reference data reads as a menu, not code. Three
pieces feed the seeder:

* ``MENU``          — categories in service order, each an item list of
                      ``(name, price_cents, shareable, popularity_weight)``.
* ``DESCRIPTIONS``  — the ingredient line shown under each item (4.1.2).
* ``CATEGORY_MODIFIERS`` / ``ITEM_MODIFIERS`` — modifier groups by *type*
                      (every burger gets the burger options, every pizza the
                      pizza options, …), with per-item overrides where a single
                      dish needs its own rules.

A modifier group is ``(name, required, min_select, max_select, [(option,
price_delta_cents), …])``; ``max_select == 0`` means unlimited.

NOTE: a few dishes are cross-listed by the house (Garlic Bread as a starter and
a side, Mac & Cheese as pasta and a side, …). Item names are used as keys here
and elsewhere, so the seeder keeps the FIRST occurrence and skips later repeats
— the dish still appears, just once.

NOTE: the e2e suite adds Classic Burger, Ribeye, Grilled Salmon and Garlic
Bread by name with a plain POST, so their categories carry only OPTIONAL groups
(a required group would reject those adds). Lamb Chops keeps a required cooking
level — the modifier-group e2e test targets it.
"""
from __future__ import annotations

# --------------------------------------------------------------------------
# Categories and items — (name, price_cents, shareable, popularity weight)
# --------------------------------------------------------------------------
MENU: dict[str, list[tuple[str, int, bool, int]]] = {
    "Starters": [
        ("Garlic Bread", 695, True, 9),
        ("Cheesy Garlic Bread", 895, True, 8),
        ("Bruschetta", 950, True, 6),
        ("Mozzarella Sticks", 1050, True, 8),
        ("Spinach Artichoke Dip", 1195, True, 6),
        ("Nachos", 1150, True, 7),
        ("Loaded Nachos", 1450, True, 8),
        ("Chicken Wings (6)", 1095, True, 8),
        ("Chicken Wings (12)", 1795, True, 7),
        ("Buffalo Wings", 1250, True, 7),
        ("BBQ Wings", 1250, True, 6),
        ("Honey Garlic Wings", 1250, True, 6),
        ("Calamari", 1450, True, 7),
        ("Coconut Shrimp", 1395, True, 6),
        ("Fried Pickles", 950, True, 5),
        ("Stuffed Mushrooms", 1150, True, 5),
        ("Potato Skins", 1095, True, 6),
        ("Pretzel Bites", 950, True, 6),
        ("Onion Rings", 850, True, 7),
        ("Spring Rolls", 950, True, 6),
    ],
    "Salads": [
        ("Caesar Salad", 1250, False, 7),
        ("Greek Salad", 1250, False, 6),
        ("Garden Salad", 1050, False, 5),
        ("Cobb Salad", 1495, False, 6),
        ("Spinach Salad", 1250, False, 5),
        ("Kale Salad", 1295, False, 5),
        ("Burrata Salad", 1595, False, 6),
        ("Caprese Salad", 1395, False, 6),
        ("Mediterranean Salad", 1350, False, 5),
        ("Quinoa Salad", 1350, False, 5),
        ("Chicken Caesar", 1595, False, 8),
        ("Steak Salad", 1795, False, 6),
        ("Shrimp Salad", 1695, False, 6),
        ("Avocado Salad", 1395, False, 5),
        ("Taco Salad", 1495, False, 6),
    ],
    "Soups": [
        ("Tomato Basil", 795, False, 6),
        ("French Onion", 950, False, 7),
        ("Chicken Noodle", 850, False, 7),
        ("Clam Chowder", 1050, False, 6),
        ("Seafood Chowder", 1150, False, 6),
        ("Mushroom Soup", 895, False, 5),
        ("Lentil Soup", 850, False, 5),
        ("Minestrone", 850, False, 5),
        ("Butternut Squash", 895, False, 5),
        ("Beef Barley", 950, False, 5),
    ],
    "Burgers": [
        ("Classic Burger", 1450, False, 9),
        ("Cheeseburger", 1550, False, 9),
        ("Bacon Burger", 1695, False, 8),
        ("BBQ Burger", 1695, False, 7),
        ("Mushroom Swiss Burger", 1695, False, 7),
        ("Double Burger", 1895, False, 8),
        ("Smokehouse Burger", 1795, False, 7),
        ("Tex Mex Burger", 1695, False, 6),
        ("Jalapeño Burger", 1650, False, 6),
        ("Blue Cheese Burger", 1750, False, 6),
        ("Hawaiian Burger", 1695, False, 6),
        ("Avocado Burger", 1695, False, 7),
        ("Veggie Burger", 1495, False, 6),
        ("Beyond Burger", 1695, False, 6),
        ("Crispy Chicken Burger", 1550, False, 8),
        ("Grilled Chicken Burger", 1550, False, 7),
        ("Nashville Chicken Burger", 1650, False, 7),
        ("Fish Burger", 1550, False, 6),
        ("Pulled Pork Burger", 1650, False, 6),
        ("Breakfast Burger", 1750, False, 6),
    ],
    "Sandwiches & Wraps": [
        ("Club Sandwich", 1450, False, 8),
        ("BLT", 1150, False, 7),
        ("Turkey Club", 1450, False, 7),
        ("Reuben", 1495, False, 6),
        ("Philly Cheesesteak", 1595, False, 8),
        ("Roast Beef Sandwich", 1450, False, 6),
        ("Pulled Pork Sandwich", 1450, False, 7),
        ("Tuna Melt", 1295, False, 6),
        ("Chicken Panini", 1395, False, 6),
        ("Buffalo Chicken Wrap", 1350, False, 7),
        ("Caesar Wrap", 1250, False, 6),
        ("Veggie Wrap", 1150, False, 5),
        ("Chicken Bacon Wrap", 1395, False, 6),
        ("Monte Cristo", 1450, False, 5),
        ("Ham & Cheese", 1150, False, 6),
    ],
    "Pasta": [
        ("Spaghetti Bolognese", 1550, False, 8),
        ("Spaghetti Meatballs", 1650, False, 8),
        ("Chicken Alfredo", 1695, False, 8),
        ("Shrimp Alfredo", 1850, False, 7),
        ("Fettuccine Alfredo", 1450, False, 7),
        ("Carbonara", 1595, False, 7),
        ("Penne Arrabbiata", 1395, False, 6),
        ("Penne Primavera", 1450, False, 5),
        ("Seafood Linguine", 1895, False, 6),
        ("Lasagna", 1650, False, 8),
        ("Baked Ziti", 1550, False, 6),
        ("Ravioli", 1595, False, 6),
        ("Tortellini Alfredo", 1595, False, 6),
        ("Pesto Pasta", 1450, False, 6),
        ("Mac & Cheese", 1250, True, 7),
    ],
    "Pizza": [
        ("Margherita", 1450, True, 9),
        ("Pepperoni", 1550, True, 9),
        ("Hawaiian", 1550, True, 7),
        ("Deluxe", 1750, True, 7),
        ("Meat Lovers", 1850, True, 8),
        ("BBQ Chicken", 1750, True, 8),
        ("Buffalo Chicken", 1750, True, 7),
        ("Vegetarian", 1650, True, 6),
        ("Four Cheese", 1650, True, 7),
        ("Prosciutto Arugula", 1850, True, 6),
        ("Mushroom Pizza", 1550, True, 6),
        ("Spinach Feta", 1650, True, 5),
        ("Supreme", 1850, True, 7),
        ("Taco Pizza", 1750, True, 5),
        ("Seafood Pizza", 1950, True, 5),
        ("Mediterranean Pizza", 1750, True, 5),
        ("BBQ Beef Pizza", 1850, True, 6),
        ("Chicken Alfredo Pizza", 1850, True, 6),
        ("Bacon Ranch Pizza", 1750, True, 6),
        ("Create Your Own Pizza", 1450, True, 6),
    ],
    "Steaks & Grill": [
        ("Ribeye", 3450, False, 8),
        ("New York Strip", 3250, False, 7),
        ("Sirloin", 2650, False, 7),
        ("Filet Mignon", 3850, False, 7),
        ("Porterhouse", 4250, False, 6),
        ("T-Bone", 3950, False, 6),
        ("Prime Rib", 3450, False, 7),
        ("Steak Frites", 2950, False, 6),
        ("Surf & Turf", 4450, False, 6),
        ("Lamb Chops", 3200, False, 4),
        ("Pork Chops", 2450, False, 5),
        ("BBQ Ribs", 2650, False, 7),
        ("Beef Skewers", 2150, False, 5),
        ("Mixed Grill", 3450, False, 6),
        ("Grilled Sausage", 1650, False, 4),
        ("Smoked Brisket", 2650, False, 6),
        ("Baby Back Ribs", 2750, False, 7),
        ("Grilled Pork Belly", 2350, False, 5),
        ("Short Ribs", 2950, False, 6),
        ("Grilled Veal Chop", 3650, False, 4),
    ],
    "Seafood": [
        ("Fish & Chips", 1650, False, 8),
        ("Grilled Salmon", 2450, False, 8),
        ("Blackened Salmon", 2550, False, 6),
        ("Garlic Shrimp", 1950, False, 6),
        ("Shrimp Scampi", 2150, False, 6),
        ("Coconut Shrimp", 1750, True, 5),
        ("Lobster Tail", 3450, False, 6),
        ("Crab Cakes", 2150, False, 6),
        ("Seafood Platter", 3850, True, 6),
        ("Mussels", 1850, True, 5),
        ("Grilled Cod", 2150, False, 5),
        ("Baked Halibut", 2750, False, 5),
        ("Tuna Steak", 2650, False, 5),
        ("Seafood Linguine", 1895, False, 5),
        ("Grilled Tilapia", 1950, False, 5),
    ],
    "Chicken": [
        ("Chicken Parmesan", 1795, False, 8),
        ("Chicken Marsala", 1750, False, 6),
        ("Lemon Chicken", 1650, False, 6),
        ("Chicken Piccata", 1750, False, 5),
        ("Grilled Chicken Breast", 1550, False, 6),
        ("Fried Chicken", 1650, False, 7),
        ("Chicken Tenders", 1350, False, 7),
        ("BBQ Chicken", 1650, False, 7),
        ("Teriyaki Chicken", 1650, False, 6),
        ("Chicken Skewers", 1550, False, 5),
        ("Chicken Curry", 1695, False, 6),
        ("Butter Chicken", 1750, False, 7),
        ("Chicken Stir Fry", 1595, False, 6),
        ("Nashville Hot Chicken", 1695, False, 6),
        ("Chicken Schnitzel", 1650, False, 5),
    ],
    "Sides": [
        ("French Fries", 550, True, 9),
        ("Sweet Potato Fries", 650, True, 7),
        ("Curly Fries", 650, True, 6),
        ("Onion Rings", 650, True, 6),
        ("Mashed Potatoes", 550, False, 6),
        ("Baked Potato", 550, False, 5),
        ("Rice Pilaf", 495, False, 4),
        ("Steamed Rice", 395, False, 4),
        ("Garlic Rice", 450, False, 4),
        ("Roasted Vegetables", 650, False, 5),
        ("Steamed Vegetables", 595, False, 4),
        ("Corn on the Cob", 495, False, 4),
        ("Mac & Cheese", 850, True, 6),
        ("Side Caesar", 650, False, 5),
        ("Side Garden Salad", 595, False, 4),
        ("Coleslaw", 450, False, 4),
        ("Garlic Mushrooms", 650, False, 4),
        ("Grilled Asparagus", 695, False, 4),
        ("Sautéed Spinach", 650, False, 4),
        ("Garlic Bread", 550, True, 5),
    ],
    "Desserts": [
        ("Cheesecake", 795, False, 7),
        ("New York Cheesecake", 895, False, 7),
        ("Chocolate Cake", 850, False, 7),
        ("Lava Cake", 950, False, 7),
        ("Brownie Sundae", 950, False, 7),
        ("Tiramisu", 895, False, 6),
        ("Apple Pie", 795, False, 6),
        ("Pecan Pie", 850, False, 5),
        ("Pumpkin Pie", 795, False, 4),
        ("Key Lime Pie", 850, False, 5),
        ("Carrot Cake", 850, False, 6),
        ("Red Velvet Cake", 895, False, 6),
        ("Crème Brûlée", 950, False, 6),
        ("Chocolate Mousse", 795, False, 5),
        ("Bread Pudding", 795, False, 4),
        ("Churros", 750, True, 6),
        ("Ice Cream", 550, False, 6),
        ("Gelato", 650, False, 5),
        ("Panna Cotta", 850, False, 4),
        ("Strawberry Shortcake", 895, False, 5),
    ],
    "Soft Drinks": [
        ("Coke", 350, False, 9),
        ("Diet Coke", 350, False, 7),
        ("Coke Zero", 350, False, 7),
        ("Sprite", 350, False, 7),
        ("Ginger Ale", 350, False, 6),
        ("Root Beer", 350, False, 6),
        ("Iced Tea", 350, False, 7),
        ("Lemonade", 395, False, 7),
        ("Orange Juice", 395, False, 6),
        ("Apple Juice", 350, False, 5),
        ("Cranberry Juice", 350, False, 4),
        ("Pineapple Juice", 350, False, 4),
        ("Bottled Water", 295, False, 6),
        ("Sparkling Water", 395, False, 5),
        ("Energy Drink", 450, False, 4),
    ],
    "Beer": [
        ("Budweiser", 650, False, 7),
        ("Bud Light", 650, False, 7),
        ("Corona", 695, False, 7),
        ("Heineken", 695, False, 7),
        ("Stella Artois", 695, False, 6),
        ("Guinness", 750, False, 6),
        ("Coors Light", 650, False, 6),
        ("Canadian", 650, False, 5),
        ("IPA", 750, False, 7),
        ("Pale Ale", 750, False, 6),
        ("Amber Ale", 750, False, 5),
        ("Pilsner", 695, False, 5),
        ("Wheat Beer", 750, False, 5),
        ("Craft Lager", 795, False, 6),
        ("Non-Alcoholic Beer", 550, False, 4),
    ],
    "Wine": [
        ("Cabernet Sauvignon", 1100, False, 7),
        ("Merlot", 1050, False, 7),
        ("Pinot Noir", 1200, False, 6),
        ("Malbec", 1100, False, 6),
        ("Shiraz", 1100, False, 5),
        ("Chardonnay", 1050, False, 7),
        ("Sauvignon Blanc", 1050, False, 7),
        ("Pinot Grigio", 1000, False, 6),
        ("Riesling", 1050, False, 5),
        ("Rosé", 1000, False, 6),
        ("Prosecco", 1150, False, 6),
        ("Sparkling Wine", 1200, False, 5),
        ("House Red", 900, False, 7),
        ("House White", 900, False, 7),
        ("Dessert Wine", 1150, False, 4),
    ],
    "Cocktails": [
        ("Margarita", 1250, False, 8),
        ("Mojito", 1250, False, 7),
        ("Cosmopolitan", 1300, False, 6),
        ("Martini", 1350, False, 6),
        ("Espresso Martini", 1395, False, 7),
        ("Old Fashioned", 1395, False, 7),
        ("Manhattan", 1395, False, 6),
        ("Negroni", 1350, False, 5),
        ("Whiskey Sour", 1295, False, 6),
        ("Moscow Mule", 1250, False, 6),
        ("Aperol Spritz", 1250, False, 6),
        ("Long Island Iced Tea", 1450, False, 6),
        ("Piña Colada", 1295, False, 6),
        ("Daiquiri", 1250, False, 5),
        ("Mai Tai", 1350, False, 5),
    ],
    "Coffee & Tea": [
        ("Espresso", 350, False, 6),
        ("Double Espresso", 450, False, 6),
        ("Americano", 395, False, 6),
        ("Cappuccino", 450, False, 7),
        ("Latte", 475, False, 8),
        ("Flat White", 475, False, 6),
        ("Mocha", 495, False, 6),
        ("Hot Chocolate", 450, False, 6),
        ("English Breakfast Tea", 350, False, 5),
        ("Green Tea", 350, False, 5),
    ],
}

# --------------------------------------------------------------------------
# Ingredient line shown under each item name (4.1.2)
# --------------------------------------------------------------------------
DESCRIPTIONS: dict[str, str] = {
    # Starters
    "Garlic Bread": "Toasted baguette, garlic butter, herbs",
    "Cheesy Garlic Bread": "Garlic bread, melted mozzarella",
    "Bruschetta": "Grilled bread, tomato, basil, balsamic",
    "Mozzarella Sticks": "Breaded mozzarella, marinara dip",
    "Spinach Artichoke Dip": "Creamy spinach, artichoke, tortilla chips",
    "Nachos": "Tortilla chips, cheese, salsa, jalapeños",
    "Loaded Nachos": "Nachos, seasoned beef, guacamole, sour cream",
    "Chicken Wings (6)": "Six wings, choice of sauce",
    "Chicken Wings (12)": "Twelve wings, choice of sauce",
    "Buffalo Wings": "Crispy wings, tangy buffalo sauce",
    "BBQ Wings": "Crispy wings, smoky BBQ glaze",
    "Honey Garlic Wings": "Crispy wings, honey garlic glaze",
    "Calamari": "Lightly fried squid, lemon aioli",
    "Coconut Shrimp": "Crispy coconut shrimp, sweet chilli",
    "Fried Pickles": "Battered pickle spears, ranch",
    "Stuffed Mushrooms": "Mushroom caps, herb cream cheese",
    "Potato Skins": "Cheddar, bacon, sour cream, chives",
    "Pretzel Bites": "Warm pretzels, beer cheese dip",
    "Onion Rings": "Beer-battered onions, chipotle mayo",
    "Spring Rolls": "Vegetable rolls, sweet chilli sauce",
    # Salads
    "Caesar Salad": "Romaine, parmesan, croutons, Caesar",
    "Greek Salad": "Cucumber, tomato, olives, feta",
    "Garden Salad": "Mixed greens, tomato, cucumber, carrot",
    "Cobb Salad": "Chicken, bacon, egg, avocado, blue cheese",
    "Spinach Salad": "Baby spinach, mushroom, egg, bacon",
    "Kale Salad": "Kale, parmesan, almonds, lemon dressing",
    "Burrata Salad": "Burrata, heirloom tomato, basil, olive oil",
    "Caprese Salad": "Tomato, mozzarella, basil, balsamic",
    "Mediterranean Salad": "Greens, olives, feta, chickpeas",
    "Quinoa Salad": "Quinoa, avocado, cucumber, herbs",
    "Chicken Caesar": "Caesar salad, grilled chicken",
    "Steak Salad": "Greens, sliced steak, blue cheese",
    "Shrimp Salad": "Greens, grilled shrimp, avocado",
    "Avocado Salad": "Greens, avocado, tomato, lime",
    "Taco Salad": "Seasoned beef, tortilla bowl, cheese, salsa",
    # Soups
    "Tomato Basil": "Creamy tomato, fresh basil",
    "French Onion": "Caramelised onion, gruyère crouton",
    "Chicken Noodle": "Chicken, egg noodles, vegetables",
    "Clam Chowder": "Creamy clam, potato, bacon",
    "Seafood Chowder": "Mixed seafood, cream, potato",
    "Mushroom Soup": "Wild mushroom, cream, thyme",
    "Lentil Soup": "Red lentil, cumin, carrot",
    "Minestrone": "Vegetables, beans, pasta, tomato",
    "Butternut Squash": "Roasted squash, cream, nutmeg",
    "Beef Barley": "Beef, barley, root vegetables",
    # Burgers
    "Classic Burger": "Beef patty, lettuce, tomato, onion, pickles",
    "Cheeseburger": "Beef patty, cheddar, lettuce, tomato",
    "Bacon Burger": "Beef patty, bacon, cheddar, BBQ sauce",
    "BBQ Burger": "Beef patty, onion rings, BBQ sauce",
    "Mushroom Swiss Burger": "Beef patty, sautéed mushroom, Swiss",
    "Double Burger": "Two beef patties, double cheese",
    "Smokehouse Burger": "Beef patty, bacon, cheddar, onion rings",
    "Tex Mex Burger": "Beef patty, jalapeño, pepper jack, salsa",
    "Jalapeño Burger": "Beef patty, jalapeños, pepper jack",
    "Blue Cheese Burger": "Beef patty, blue cheese, caramelised onion",
    "Hawaiian Burger": "Beef patty, grilled pineapple, teriyaki",
    "Avocado Burger": "Beef patty, avocado, Swiss, lettuce",
    "Veggie Burger": "House veggie patty, lettuce, tomato",
    "Beyond Burger": "Plant-based patty, vegan cheese",
    "Crispy Chicken Burger": "Fried chicken, lettuce, mayo",
    "Grilled Chicken Burger": "Grilled chicken, lettuce, tomato",
    "Nashville Chicken Burger": "Spicy fried chicken, pickles, slaw",
    "Fish Burger": "Battered cod, tartar, lettuce",
    "Pulled Pork Burger": "Pulled pork, slaw, BBQ sauce",
    "Breakfast Burger": "Beef patty, fried egg, bacon, hash brown",
    # Sandwiches & Wraps
    "Club Sandwich": "Turkey, bacon, lettuce, tomato, mayo",
    "BLT": "Bacon, lettuce, tomato, mayo",
    "Turkey Club": "Roast turkey, bacon, triple-stacked",
    "Reuben": "Corned beef, sauerkraut, Swiss, rye",
    "Philly Cheesesteak": "Steak, peppers, onions, cheese",
    "Roast Beef Sandwich": "Roast beef, horseradish, ciabatta",
    "Pulled Pork Sandwich": "Pulled pork, slaw, BBQ, brioche",
    "Tuna Melt": "Tuna salad, melted cheddar, sourdough",
    "Chicken Panini": "Grilled chicken, pesto, mozzarella",
    "Buffalo Chicken Wrap": "Crispy chicken, buffalo, ranch, lettuce",
    "Caesar Wrap": "Chicken, romaine, parmesan, Caesar",
    "Veggie Wrap": "Hummus, grilled vegetables, greens",
    "Chicken Bacon Wrap": "Grilled chicken, bacon, ranch",
    "Monte Cristo": "Ham, turkey, Swiss, battered, fried",
    "Ham & Cheese": "Black forest ham, cheddar, mustard",
    # Pasta
    "Spaghetti Bolognese": "Beef ragù, tomato, parmesan",
    "Spaghetti Meatballs": "Beef meatballs, marinara, parmesan",
    "Chicken Alfredo": "Grilled chicken, creamy alfredo",
    "Shrimp Alfredo": "Shrimp, creamy alfredo, parmesan",
    "Fettuccine Alfredo": "Fettuccine, creamy parmesan sauce",
    "Carbonara": "Pancetta, egg, parmesan, black pepper",
    "Penne Arrabbiata": "Penne, spicy tomato, garlic, chilli",
    "Penne Primavera": "Penne, seasonal vegetables, olive oil",
    "Seafood Linguine": "Mixed seafood, white wine, garlic",
    "Lasagna": "Layered beef, béchamel, mozzarella",
    "Baked Ziti": "Ziti, marinara, ricotta, mozzarella",
    "Ravioli": "Cheese ravioli, tomato basil sauce",
    "Tortellini Alfredo": "Cheese tortellini, creamy alfredo",
    "Pesto Pasta": "Basil pesto, parmesan, pine nuts",
    "Mac & Cheese": "Three-cheese sauce, baked crumb",
    # Pizza
    "Margherita": "Tomato, mozzarella, fresh basil",
    "Pepperoni": "Tomato, mozzarella, pepperoni",
    "Hawaiian": "Ham, pineapple, mozzarella",
    "Deluxe": "Pepperoni, sausage, peppers, mushroom",
    "Meat Lovers": "Pepperoni, sausage, bacon, ham",
    "BBQ Chicken": "BBQ sauce, chicken, red onion",
    "Buffalo Chicken": "Buffalo chicken, ranch, mozzarella",
    "Vegetarian": "Peppers, mushroom, onion, olives",
    "Four Cheese": "Mozzarella, cheddar, parmesan, gorgonzola",
    "Prosciutto Arugula": "Prosciutto, arugula, parmesan",
    "Mushroom Pizza": "Mixed mushrooms, mozzarella, thyme",
    "Spinach Feta": "Spinach, feta, garlic, mozzarella",
    "Supreme": "Pepperoni, sausage, peppers, onion, olives",
    "Taco Pizza": "Seasoned beef, salsa, cheddar, lettuce",
    "Seafood Pizza": "Shrimp, calamari, garlic, mozzarella",
    "Mediterranean Pizza": "Olives, feta, tomato, red onion",
    "BBQ Beef Pizza": "BBQ beef, red onion, mozzarella",
    "Chicken Alfredo Pizza": "Alfredo, grilled chicken, mozzarella",
    "Bacon Ranch Pizza": "Bacon, ranch, chicken, mozzarella",
    "Create Your Own Pizza": "Build your own, choose your toppings",
    # Steaks & Grill
    "Ribeye": "12oz ribeye, hand-cut, chimichurri",
    "New York Strip": "10oz striploin, herb butter",
    "Sirloin": "8oz sirloin, garlic butter",
    "Filet Mignon": "7oz tenderloin, red wine jus",
    "Porterhouse": "20oz porterhouse, grilled",
    "T-Bone": "18oz T-bone, herb butter",
    "Prime Rib": "Slow-roasted prime rib, au jus",
    "Steak Frites": "Sirloin, fries, peppercorn sauce",
    "Surf & Turf": "Filet, lobster tail, drawn butter",
    "Lamb Chops": "Herb-crusted lamb, red wine jus",
    "Pork Chops": "Grilled pork chops, apple sauce",
    "BBQ Ribs": "Slow-cooked ribs, BBQ glaze",
    "Beef Skewers": "Marinated beef, peppers, onion",
    "Mixed Grill": "Steak, sausage, chicken, chop",
    "Grilled Sausage": "Grilled sausages, mustard, onions",
    "Smoked Brisket": "Slow-smoked brisket, BBQ sauce",
    "Baby Back Ribs": "Pork ribs, smoky glaze",
    "Grilled Pork Belly": "Crispy pork belly, apple slaw",
    "Short Ribs": "Braised beef short ribs, red wine",
    "Grilled Veal Chop": "Veal chop, rosemary, jus",
    # Seafood
    "Fish & Chips": "Battered cod, fries, tartar",
    "Grilled Salmon": "Atlantic salmon, seasonal greens",
    "Blackened Salmon": "Cajun-spiced salmon, lemon",
    "Garlic Shrimp": "Sautéed shrimp, garlic butter",
    "Shrimp Scampi": "Shrimp, garlic, white wine, linguine",
    "Lobster Tail": "Grilled lobster tail, drawn butter",
    "Crab Cakes": "Pan-seared crab cakes, remoulade",
    "Seafood Platter": "Shrimp, calamari, fish, mussels",
    "Mussels": "Steamed mussels, white wine, garlic",
    "Grilled Cod": "Grilled cod, lemon, herbs",
    "Baked Halibut": "Baked halibut, butter, capers",
    "Tuna Steak": "Seared tuna, sesame, soy glaze",
    "Grilled Tilapia": "Grilled tilapia, lemon butter",
    # Chicken
    "Chicken Parmesan": "Breaded chicken, marinara, mozzarella",
    "Chicken Marsala": "Chicken, mushroom, marsala sauce",
    "Lemon Chicken": "Pan-seared chicken, lemon butter",
    "Chicken Piccata": "Chicken, capers, lemon, white wine",
    "Grilled Chicken Breast": "Herb-marinated grilled chicken",
    "Fried Chicken": "Buttermilk fried chicken",
    "Chicken Tenders": "Breaded tenders, choice of dip",
    "Teriyaki Chicken": "Grilled chicken, teriyaki glaze",
    "Chicken Skewers": "Marinated chicken, peppers",
    "Chicken Curry": "Chicken, coconut curry, rice",
    "Butter Chicken": "Creamy tomato curry, basmati rice",
    "Chicken Stir Fry": "Chicken, vegetables, soy, rice",
    "Nashville Hot Chicken": "Spicy fried chicken, pickles",
    "Chicken Schnitzel": "Breaded chicken cutlet, lemon",
    # Sides
    "French Fries": "Crispy golden fries",
    "Sweet Potato Fries": "Sweet potato fries, chipotle mayo",
    "Curly Fries": "Seasoned curly fries",
    "Mashed Potatoes": "Buttery mashed potatoes",
    "Baked Potato": "Baked potato, sour cream, chives",
    "Rice Pilaf": "Seasoned rice pilaf",
    "Steamed Rice": "Steamed white rice",
    "Garlic Rice": "Garlic-buttered rice",
    "Roasted Vegetables": "Seasonal roasted vegetables",
    "Steamed Vegetables": "Steamed seasonal vegetables",
    "Corn on the Cob": "Buttered corn on the cob",
    "Side Caesar": "Small Caesar salad",
    "Side Garden Salad": "Small mixed green salad",
    "Coleslaw": "Creamy cabbage slaw",
    "Garlic Mushrooms": "Sautéed garlic mushrooms",
    "Grilled Asparagus": "Grilled asparagus, sea salt",
    "Sautéed Spinach": "Garlic sautéed spinach",
    # Desserts
    "Cheesecake": "Classic baked cheesecake",
    "New York Cheesecake": "Rich cheesecake, berry compote",
    "Chocolate Cake": "Moist chocolate layer cake",
    "Lava Cake": "Warm chocolate centre, ice cream",
    "Brownie Sundae": "Fudge brownie, ice cream, sauce",
    "Tiramisu": "Espresso, mascarpone, cocoa",
    "Apple Pie": "Cinnamon apple pie, à la mode",
    "Pecan Pie": "Buttery pecan pie",
    "Pumpkin Pie": "Spiced pumpkin pie, cream",
    "Key Lime Pie": "Tangy key lime pie",
    "Carrot Cake": "Spiced carrot cake, cream cheese",
    "Red Velvet Cake": "Red velvet, cream cheese frosting",
    "Crème Brûlée": "Vanilla custard, caramelised sugar",
    "Chocolate Mousse": "Silky dark chocolate mousse",
    "Bread Pudding": "Warm bread pudding, caramel",
    "Churros": "Cinnamon churros, chocolate dip",
    "Ice Cream": "Three scoops, choice of flavours",
    "Gelato": "Italian gelato, choice of flavours",
    "Panna Cotta": "Vanilla panna cotta, berries",
    "Strawberry Shortcake": "Sponge, strawberries, cream",
    # Soft Drinks
    "Coke": "Coca-Cola",
    "Diet Coke": "Diet Coca-Cola",
    "Coke Zero": "Coca-Cola Zero Sugar",
    "Sprite": "Lemon-lime soda",
    "Ginger Ale": "Canada Dry ginger ale",
    "Root Beer": "Classic root beer",
    "Iced Tea": "Freshly brewed iced tea",
    "Lemonade": "House-made lemonade",
    "Orange Juice": "Fresh orange juice",
    "Apple Juice": "Apple juice",
    "Cranberry Juice": "Cranberry juice",
    "Pineapple Juice": "Pineapple juice",
    "Bottled Water": "Still spring water",
    "Sparkling Water": "Sparkling mineral water",
    "Energy Drink": "Chilled energy drink",
    # Beer
    "Budweiser": "American lager",
    "Bud Light": "Light lager",
    "Corona": "Mexican lager, lime",
    "Heineken": "Dutch pilsner",
    "Stella Artois": "Belgian pilsner",
    "Guinness": "Irish dry stout",
    "Coors Light": "Light lager",
    "Canadian": "Molson Canadian lager",
    "IPA": "Hoppy India pale ale",
    "Pale Ale": "Balanced pale ale",
    "Amber Ale": "Malty amber ale",
    "Pilsner": "Crisp pilsner",
    "Wheat Beer": "Cloudy wheat beer",
    "Craft Lager": "Local craft lager",
    "Non-Alcoholic Beer": "Alcohol-free lager",
    # Wine
    "Cabernet Sauvignon": "Full-bodied red",
    "Merlot": "Smooth medium red",
    "Pinot Noir": "Light, elegant red",
    "Malbec": "Bold Argentine red",
    "Shiraz": "Spicy full red",
    "Chardonnay": "Oaked white",
    "Sauvignon Blanc": "Crisp, citrus white",
    "Pinot Grigio": "Light, dry white",
    "Riesling": "Off-dry aromatic white",
    "Rosé": "Dry, fruity rosé",
    "Prosecco": "Italian sparkling",
    "Sparkling Wine": "Brut sparkling",
    "House Red": "House red blend",
    "House White": "House white blend",
    "Dessert Wine": "Sweet late-harvest",
    # Cocktails
    "Margarita": "Tequila, lime, triple sec",
    "Mojito": "Rum, mint, lime, soda",
    "Cosmopolitan": "Vodka, cranberry, lime",
    "Martini": "Gin or vodka, vermouth",
    "Espresso Martini": "Vodka, coffee liqueur, espresso",
    "Old Fashioned": "Bourbon, bitters, sugar",
    "Manhattan": "Rye, sweet vermouth, bitters",
    "Negroni": "Gin, Campari, vermouth",
    "Whiskey Sour": "Whiskey, lemon, sugar",
    "Moscow Mule": "Vodka, ginger beer, lime",
    "Aperol Spritz": "Aperol, prosecco, soda",
    "Long Island Iced Tea": "Five spirits, cola, lemon",
    "Piña Colada": "Rum, coconut, pineapple",
    "Daiquiri": "Rum, lime, sugar",
    "Mai Tai": "Rum, orange, almond, lime",
    # Coffee & Tea
    "Espresso": "Single shot espresso",
    "Double Espresso": "Double shot espresso",
    "Americano": "Espresso, hot water",
    "Cappuccino": "Espresso, steamed milk, foam",
    "Latte": "Espresso, steamed milk",
    "Flat White": "Espresso, microfoam milk",
    "Mocha": "Espresso, chocolate, steamed milk",
    "Hot Chocolate": "Rich hot chocolate, cream",
    "English Breakfast Tea": "Black breakfast tea",
    "Green Tea": "Loose-leaf green tea",
}

# --------------------------------------------------------------------------
# Modifier groups by TYPE — applied to every item in the category unless the
# item has its own override in ITEM_MODIFIERS below.
#   (group, required, min_select, max_select, [(option, price_delta_cents)])
# --------------------------------------------------------------------------
_COOK_LEVELS = [
    ("Rare", 0), ("Medium Rare", 0), ("Medium", 0),
    ("Medium Well", 0), ("Well Done", 0),
]

CATEGORY_MODIFIERS: dict[str, list] = {
    "Starters": [
        ("Dip", False, 0, 1,
         [("Ranch", 0), ("Marinara", 0), ("Garlic aioli", 0), ("Blue cheese", 0)]),
        ("Add-ons", False, 0, 0, [("Extra dip", 100), ("Extra portion", 300)]),
    ],
    "Salads": [
        ("Add protein", False, 0, 1,
         [("Grilled chicken", 500), ("Grilled shrimp", 700),
          ("Grilled salmon", 800), ("Sliced steak", 900)]),
        ("Dressing", False, 0, 1,
         [("Ranch", 0), ("Caesar", 0), ("Balsamic", 0), ("Greek", 0), ("On the side", 0)]),
    ],
    "Soups": [
        ("Size", False, 0, 1, [("Cup", 0), ("Bowl", 300)]),
        ("Bread", False, 0, 1, [("Sourdough roll", 0), ("Baguette", 0), ("No bread", 0)]),
    ],
    "Burgers": [
        ("Cooking level", False, 0, 1, list(_COOK_LEVELS)),
        ("Cheese", False, 0, 1,
         [("American", 0), ("Cheddar", 100), ("Swiss", 100), ("Blue cheese", 150)]),
        ("Add-ons", False, 0, 0,
         [("Bacon", 200), ("Fried egg", 150), ("Avocado", 200), ("Extra patty", 400)]),
        ("Side", False, 0, 1,
         [("Fries", 0), ("Sweet potato fries", 150), ("Side salad", 0), ("Onion rings", 200)]),
    ],
    "Sandwiches & Wraps": [
        ("Bread", False, 0, 1,
         [("White", 0), ("Whole wheat", 0), ("Sourdough", 0), ("Ciabatta", 0), ("Wrap", 0)]),
        ("Side", False, 0, 1,
         [("Fries", 0), ("Side salad", 0), ("Cup of soup", 200), ("Coleslaw", 0)]),
        ("Add-ons", False, 0, 0, [("Bacon", 200), ("Cheese", 100), ("Avocado", 200)]),
    ],
    "Pasta": [
        ("Add protein", False, 0, 1,
         [("Grilled chicken", 500), ("Shrimp", 700), ("Meatballs", 400)]),
        ("Add-ons", False, 0, 0,
         [("Extra parmesan", 150), ("Garlic bread", 300), ("Chilli flakes", 0)]),
    ],
    "Pizza": [
        ("Size", True, 1, 1,
         [('10" Small', 0), ('12" Medium', 300), ('14" Large', 600)]),
        ("Crust", False, 0, 1,
         [("Classic", 0), ("Thin", 0), ("Gluten-free", 250), ("Stuffed crust", 300)]),
        ("Extra toppings", False, 0, 0,
         [("Extra cheese", 200), ("Pepperoni", 200), ("Mushrooms", 150),
          ("Olives", 100), ("Jalapeños", 100)]),
    ],
    "Steaks & Grill": [
        ("Cooking level", False, 0, 1, list(_COOK_LEVELS)),
        ("Sauce", False, 0, 1,
         [("None", 0), ("Peppercorn", 150), ("Béarnaise", 150),
          ("Mushroom", 150), ("Red wine jus", 150)]),
        ("Add-ons", False, 0, 0,
         [("Grilled shrimp", 600), ("Grilled mushrooms", 200), ("Truffle butter", 250)]),
    ],
    "Seafood": [
        ("Side", False, 0, 1,
         [("Fries", 0), ("Mashed potato", 0), ("Rice", 0),
          ("Side salad", 0), ("Seasonal veg", 0)]),
        ("Sauce", False, 0, 1,
         [("Tartar", 0), ("Lemon butter", 0), ("Garlic aioli", 0), ("Cocktail", 0)]),
    ],
    "Chicken": [
        ("Side", False, 0, 1,
         [("Fries", 0), ("Mashed potato", 0), ("Rice", 0),
          ("Side salad", 0), ("Seasonal veg", 0)]),
        ("Spice", False, 0, 1, [("Mild", 0), ("Medium", 0), ("Hot", 0)]),
        ("Add-ons", False, 0, 0, [("Extra sauce", 100), ("Cheese", 100)]),
    ],
    "Sides": [
        ("Size", False, 0, 1, [("Regular", 0), ("Large", 250)]),
        ("Add-ons", False, 0, 0, [("Cheese", 100), ("Gravy", 100), ("Bacon bits", 150)]),
    ],
    "Desserts": [
        ("Serve with", False, 0, 1,
         [("Vanilla ice cream", 150), ("Whipped cream", 0),
          ("Berry compote", 100), ("On its own", 0)]),
    ],
    "Soft Drinks": [
        ("Size", False, 0, 1, [("Regular", 0), ("Large", 100)]),
        ("Ice", False, 0, 1, [("Regular ice", 0), ("Light ice", 0), ("No ice", 0)]),
    ],
    "Beer": [
        ("Size", False, 0, 1, [("Pint", 0), ("Half pint", -300)]),
    ],
    "Wine": [
        ("Pour", True, 1, 1, [("6 oz", 0), ("9 oz", 400), ("Bottle", 2500)]),
    ],
    "Cocktails": [
        ("Make it a double", False, 0, 1, [("Single", 0), ("Double", 400)]),
    ],
    "Coffee & Tea": [
        ("Milk", False, 0, 1,
         [("None", 0), ("Whole", 0), ("Skim", 0), ("Oat", 60), ("Almond", 60), ("Soy", 60)]),
        ("Size", False, 0, 1, [("Regular", 0), ("Large", 80)]),
        ("Extra", False, 0, 0, [("Extra shot", 80), ("Decaf", 0), ("Vanilla syrup", 50)]),
    ],
}

_WING_SAUCES = [
    ("Buffalo", 0), ("BBQ", 0), ("Honey Garlic", 0),
    ("Salt & Pepper", 0), ("Lemon Pepper", 0), ("Plain", 0),
]
_WING_HEAT = ("Heat", False, 0, 1,
              [("Mild", 0), ("Medium", 0), ("Hot", 0), ("Extra hot", 0)])
_WING_DIP = ("Dip", False, 0, 1, [("Ranch", 0), ("Blue cheese", 0)])

# Per-item overrides — replace the category template for this one dish.
ITEM_MODIFIERS: dict[str, list] = {
    # Wings pick a sauce (already-flavoured ones just pick heat/dip).
    "Chicken Wings (6)": [
        ("Sauce", True, 1, 1, list(_WING_SAUCES)), _WING_HEAT, _WING_DIP,
    ],
    "Chicken Wings (12)": [
        ("Sauce", True, 1, 1, list(_WING_SAUCES)), _WING_HEAT, _WING_DIP,
    ],
    "Buffalo Wings": [_WING_HEAT, _WING_DIP],
    "BBQ Wings": [_WING_HEAT, _WING_DIP],
    "Honey Garlic Wings": [_WING_HEAT, _WING_DIP],
    # Lamb Chops — required cooking level (the modifier-group e2e test targets
    # this) plus a priced "Extra chop" add-on.
    "Lamb Chops": [
        ("Cooking level", True, 1, 1, list(_COOK_LEVELS)),
        ("Sauce", False, 0, 1,
         [("None", 0), ("Peppercorn", 150), ("Béarnaise", 150),
          ("Mint jelly", 0), ("Red wine jus", 0)]),
        ("Add-ons", False, 0, 0,
         [("Extra chop", 600), ("Grilled mushrooms", 200), ("Truffle butter", 250)]),
    ],
    # Build-your-own pizza — size/crust/sauce required, toppings open.
    "Create Your Own Pizza": [
        ("Size", True, 1, 1,
         [('10" Small', 0), ('12" Medium', 300), ('14" Large', 600)]),
        ("Crust", True, 1, 1,
         [("Classic", 0), ("Thin", 0), ("Thick", 0), ("Gluten-free", 250)]),
        ("Sauce", True, 1, 1,
         [("Tomato", 0), ("BBQ", 0), ("Alfredo", 0), ("Pesto", 100)]),
        ("Toppings", False, 0, 0,
         [("Pepperoni", 200), ("Mushroom", 150), ("Onion", 100), ("Peppers", 100),
          ("Olives", 100), ("Bacon", 200), ("Chicken", 250), ("Extra cheese", 200),
          ("Pineapple", 100), ("Jalapeños", 100)]),
    ],
    # Ice cream / gelato — pick scoop flavours.
    "Ice Cream": [
        ("Flavours", True, 1, 3,
         [("Vanilla", 0), ("Chocolate", 0), ("Strawberry", 0),
          ("Mint choc chip", 0), ("Cookies & cream", 0)]),
    ],
    "Gelato": [
        ("Flavours", True, 1, 2,
         [("Vanilla", 0), ("Chocolate", 0), ("Pistachio", 100),
          ("Stracciatella", 0), ("Salted caramel", 0)]),
    ],
}


def modifier_groups_for(item_name: str, category_name: str) -> list:
    """The modifier groups for an item: its override, else the category set."""
    if item_name in ITEM_MODIFIERS:
        return ITEM_MODIFIERS[item_name]
    return CATEGORY_MODIFIERS.get(category_name, [])
