"""Menu item -> photo URL, applied by the seed so any fresh database
(a new Cloud Run / Postgres) shows the photos that have been linked.

Generated from the linked images; keep in step when new photos are added.
The image files themselves live in web/static/img/menu/ (baked into the image).
"""

IMAGE_URLS = {
    'Avocado Burger': '/static/img/menu/avocado_burger.png',
    'Avocado Salad': '/static/img/menu/avocado_salad.png',
    'Bacon Burger': '/static/img/menu/bacon_burger.png',
    'BBQ Burger': '/static/img/menu/bbq_burger.png',
    'BBQ Wings': '/static/img/menu/bbq_wings.png',
    'Beef Barley': '/static/img/menu/beef_barley.png',
    'Beyond Burger': '/static/img/menu/beyond_burger.png',
    'BLT': '/static/img/menu/blt.png',
    'Blue Cheese Burger': '/static/img/menu/blue_cheese_burger.png',
    'Breakfast Burger': '/static/img/menu/breakfast_burger.png',
    'Bruschetta': '/static/img/menu/bruschetta.png',
    'Buffalo Chicken Wrap': '/static/img/menu/buffalo_chicken_wrap.png',
    'Buffalo Wings': '/static/img/menu/buffalo_wings.png',
    'Burrata Salad': '/static/img/menu/burrata_salad.png',
    'Butternut Squash': '/static/img/menu/butternut_squash.png',
    'Caesar Salad': '/static/img/menu/caesar_salad.png',
    'Caesar Wrap': '/static/img/menu/caesar_wrap.png',
    'Calamari': '/static/img/menu/calamari.png',
    'Caprese Salad': '/static/img/menu/caprese_salad.png',
    'Cheeseburger': '/static/img/menu/cheeseburger.png',
    'Cheesy Garlic Bread': '/static/img/menu/cheesy_garlic_bread.png',
    'Chicken Bacon Wrap': '/static/img/menu/chicken_bacon_wrap.png',
    'Chicken Caesar': '/static/img/menu/chicken_caesar.png',
    'Chicken Noodle': '/static/img/menu/chicken_noodle.png',
    'Chicken Panini': '/static/img/menu/chicken_panini.png',
    'Chicken Wings (12)': '/static/img/menu/chicken_wings_12.png',
    'Chicken Wings (6)': '/static/img/menu/chicken_wings_6.png',
    'Clam Chowder': '/static/img/menu/clam_chowder.png',
    'Classic Burger': '/static/img/menu/classic_burger.png',
    'Club Sandwich': '/static/img/menu/club_sandwich.png',
    'Cobb Salad': '/static/img/menu/cobb_salad.png',
    'Coconut Shrimp': '/static/img/menu/coconut_shrimp.png',
    'Crispy Chicken Burger': '/static/img/menu/crispy_chicken_burger.png',
    'Double Burger': '/static/img/menu/double_burger.png',
    'Fish Burger': '/static/img/menu/fish_burger.png',
    'French Onion': '/static/img/menu/french_onion.png',
    'Fried Pickles': '/static/img/menu/fried_pickles.png',
    'Garden Salad': '/static/img/menu/garden_salad.png',
    'Garlic Bread': '/static/img/menu/garlic_bread.png',
    'Greek Salad': '/static/img/menu/greek_salad.png',
    'Grilled Chicken Burger': '/static/img/menu/grilled_chicken_burger.png',
    'Ham & Cheese': '/static/img/menu/ham_and_cheese.png',
    'Hawaiian Burger': '/static/img/menu/hawaiian_burger.png',
    'Honey Garlic Wings': '/static/img/menu/honey_garlic_wings.png',
    'Jalapeño Burger': '/static/img/menu/jalapeno_burger.png',
    'Kale Salad': '/static/img/menu/kale_salad.png',
    'Lentil Soup': '/static/img/menu/lentil_soup.png',
    'Loaded Nachos': '/static/img/menu/loaded_nachos.png',
    'Mediterranean Salad': '/static/img/menu/mediterranean_salad.png',
    'Minestrone': '/static/img/menu/minestrone.png',
    'Monte Cristo': '/static/img/menu/monte_cristo.png',
    'Mozzarella Sticks': '/static/img/menu/mozzarella_sticks.png',
    'Mushroom Soup': '/static/img/menu/mushroom_soup.png',
    'Mushroom Swiss Burger': '/static/img/menu/mushroom_swiss_burger.png',
    'Nachos': '/static/img/menu/nachos.png',
    'Nashville Chicken Burger': '/static/img/menu/nashville_chicken_burger.png',
    'Onion Rings': '/static/img/menu/onion_rings.png',
    'Philly Cheesesteak': '/static/img/menu/philly_cheesesteak.png',
    'Potato Skins': '/static/img/menu/potato_skins.png',
    'Pretzel Bites': '/static/img/menu/pretzel_bites.png',
    'Pulled Pork Burger': '/static/img/menu/pulled_pork_burger.png',
    'Pulled Pork Sandwich': '/static/img/menu/pulled_pork_sandwich.png',
    'Quinoa Salad': '/static/img/menu/quinoa_salad.png',
    'Reuben': '/static/img/menu/reuben.png',
    'Roast Beef Sandwich': '/static/img/menu/roast_beef_sandwich.png',
    'Seafood Chowder': '/static/img/menu/seafood_chowder.png',
    'Shrimp Salad': '/static/img/menu/shrimp_salad.png',
    'Smokehouse Burger': '/static/img/menu/smokehouse_burger.png',
    'Spinach Artichoke Dip': '/static/img/menu/spinach_artichoke_dip.png',
    'Spinach Salad': '/static/img/menu/spinach_salad.png',
    'Spring Rolls': '/static/img/menu/spring_rolls.png',
    'Steak Salad': '/static/img/menu/steak_salad.png',
    'Stuffed Mushrooms': '/static/img/menu/stuffed_mushrooms.png',
    'Taco Salad': '/static/img/menu/taco_salad.png',
    'Tex Mex Burger': '/static/img/menu/tex_mex_burger.png',
    'Tomato Basil': '/static/img/menu/tomato_basil.png',
    'Tuna Melt': '/static/img/menu/tuna_melt.png',
    'Turkey Club': '/static/img/menu/turkey_club.png',
    'Veggie Burger': '/static/img/menu/veggie_burger.png',
    'Veggie Wrap': '/static/img/menu/veggie_wrap.png',
}
